=== xingguangli/revbayes/help_html/rb-help-entry.xsd
<?xml version="1.0"?>    
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.revbayes.com/schema/help-entry" >
   
    <xs:element name="revbayes-help">
        <xs:annotation>
            <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                Fill in with more help documentation ...
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="function-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:annotation>
                                    <xs:documentation>Full description, text is sectioned by paragraphs.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="usage"/>
                            <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Arguments is optional since functions can have 0 parameters.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="label"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="argumentType"/>
                                        <xs:element type="xs:string" name="valueType"/>  
                                        <xs:element type="xs:string" name="option" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="defaultValue" minOccurs="0"/>                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="returnValue"/>
                                                        
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>Text sectioned with paragraphs.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="example" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Typically, example text will be wrapped in a CDATA section to avoid having to escape special characters.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                        <xs:element type="xs:anyURI" name="url" minOccurs="0"/>
                                        <xs:element type="xs:string" name="doi" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="author"/>
                            
                            <xs:element name="seeAlso" minOccurs="0">                                
                                <xs:annotation>
                                    <xs:documentation>The xslt page will try to auto generate links to the referred help entries, therefore
                                        only exact names of help items should be listed here (case sensitive).</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="entry" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="type-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="memberMethod" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="methodName"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="usage"/>
                                        <xs:element type="xs:string" name="methodType"/>
                                        <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="label"/>
                                                    <xs:element type="xs:string" name="description"/>
                                                    <xs:element type="xs:string" name="argumentType"/>
                                                    <xs:element type="xs:string" name="valueType"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="returnValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="author"/>
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xingguangli/revbayes/deprecated/help/exp.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>exp</name>

        <title>Exponential value of a number.</title>
    
        <description>
            <p>
            The 'exp' function returns the exponential value of a number.
            </p>
        </description>

        <usage>
            <![CDATA[
             exp( Real x )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The number whose exponential needs to be computed.</description>
            <valueType>Real</valueType>
        </argument>

        <returnValue>RealPos, Real, RevObject</returnValue>

        <example>
            <![CDATA[
             # Let's compute the exponential of a few numbers
             exp(-1)
             exp(0)
             exp(1)
             exp(10)
             # ln is the exponential's inverse function
             ln(exp(10))
             # Another way of achieving the same thing:
             log(exp(10),base=exp(1))
             ]]>

        </example>


        <author>Bastien Boussau</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>ln</entry>
            <entry>log</entry>
            <entry>power</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/mapTree.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>mapTree</name>

        <title>Maximum a posteriori tree</title>
    
        <description>
            <p>
            Finds the tree with the highest posterior probability.
            </p>
        </description>

        <usage>
            <![CDATA[
             mapTree( TreeTrace treetrace, String file )
             ]]> 
        </usage>
    
        <argument>
            <label>treetrace</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The tree trace in which we will search for the tree with the highest posterior probability.</description>
            <valueType>TreeTrace</valueType>
        </argument>
        <argument>
            <label>file</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A description of the argument.</description>
            <valueType>String</valueType>
        </argument>

        <returnValue>Tree, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            This function searches through the tree trace and finds the topology with the most occurrences (highest posterior probability).
            Then, we use the mean branch lengths or node ages to build the tree.
            </p>
        </details>

        <example>
            <![CDATA[
             treetrace = readTreeTrace("output/primates.trees", treetype="non-clock")
             mapTree(treetrace,"output/primates_map.tree")
             ]]>

        </example>

        <author>Sebastian Hoehna</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>readTreeTrace</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/sqrt.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>sqrt</name>

        <title>Square root</title>
    
        <description>
            <p>
            'sqrt' computes the square root of a real positive number, 'x'.
            </p>
        </description>

        <usage>
            <![CDATA[
             sqrt( RealPos x )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The value</description>
            <valueType>RealPos</valueType>
        </argument>

        <returnValue>RealPos, Real, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            'sqrt' computes the square root of the real positive number, 'x', and returns the square-root as a real positive number. 'sqrt(x)' is equivalent to raising 'x' to the power 0.5.
            </p>
        </details>

        <example>
            <![CDATA[
            > sqrt(2)
                1.41421
            > sqrt(2) == 2^0.5
                true
            ]]>

        </example>

        <author>Michael Landis</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>power</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/dcat.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>rcat</name>

        <title>Probability of the Categorical Distribution</title>
    
        <description>
            <p>
            This function computes the probability mass of an observation x from a
            categorical distribution. The probability of the outcomes is specified
            by the simplex parameter p. The outcomes are labeled from 1 to K, and
            each outcome i has the probability given by element i in the simplex p.
            </p>
        </description>

        <usage>
            <![CDATA[
             dcat( Natural x, Simplex p, Bool log = true )
             ]]>
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The observation.</description>
            <valueType>Natural</valueType>
        </argument>
        <argument>
            <label>p</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The probability of the outcomes.</description>
            <valueType>Simplex</valueType>
        </argument>
        <argument>
            <label>log</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>If TRUE, the probability p is given as log(p).</description>
            <valueType>Bool</valueType>
        </argument>

        <returnValue>Real</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            See dnCat for details.
            </p>
        </details>

        <example>
            <![CDATA[
             # Compute the density of each of the outcomes
             # in a categorical distribution with the outcome
             # probabilities being 0.1, 0.2, 0.3, and 0.4,
             # respectively. Note that the outcomes are
             # in the set { 1, 2, 3, 4 }
             x <- v( 1, 2, 3, 4 )
             for ( i in 1:x.size() )
                y[i] <- dcat( x[i], simplex( 0.1, 0.2, 0.3, 0.4 ), FALSE )
             y
             ]]>

        </example>

        <author>Fredrik Ronquist</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>dnCat</entry>
            <entry>rcat</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/log.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>log</name>

        <title>Logarithm function.</title>
    
        <description>
            <p>
            The "log" function computes the logarithm of a number, given a particular base.
            </p>
        </description>

        <usage>
            <![CDATA[
             log( RealPos x, RealPos base )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The number whose logarithm needs to be computed.</description>
            <valueType>RealPos</valueType>
        </argument>
        <argument>
            <label>base</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The base for computing the logarithm.</description>
            <valueType>RealPos</valueType>
        </argument>

        <returnValue>Real, RevObject</returnValue>


        <example>
            <![CDATA[
             # Let's compute the logarithm of a few numbers, changing the base
             log(1, base=exp(1))
             log(1, base=2)
             log(2, base=2)
             log(4, base=2)
             log(8, base=2)
             log(10, base=10)
             log(100, base=10)
             log(100, base=10.5)
             # Let's see what happens when we go beyond the definition range of log
             log(-1, base=10)
             ]]>

        </example>


        <author>Bastien Boussau</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
			<entry>ln</entry>
            <entry>exp</entry>
            <entry>power</entry>
                    </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/normalize.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>normalize</name>

        <title>Normalize a vector of values</title>
    
        <description>
            <p>
            'normalize' scales all vector elements by some constant such that their new average equals 'sum'.
            </p>
        </description>

        <usage>
            <![CDATA[
             normalize( RealPos[] x, RealPos sum = 1 )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A description of the argument.</description>
            <valueType>RealPos[]</valueType>
        </argument>
        <argument>
            <label>sum</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A description of the argument.</description>
            <valueType>RealPos</valueType>
            <defaultValue>1</defaultValue>
        </argument>

        <returnValue>RealPos[], ModelObject, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            'normalize' computes the mean of 'x', divides all elements in 'x' by that mean, then multiplies by the value 'sum'. This results in the mean of 'normalize(x)' equaling 'sum'.
            </p>
        </details>

        <example>
            <![CDATA[
            > x <- [1, 1, 3]
            > y := normalize(x, 4.0)
            > y
               [ 2, 4, 6 ]

            ]]>

        </example>

        <author>Michael Landis</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>similar function</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/fnDPPMeanFromConc.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>fnDPPMeanFromConc</name>

        <title>The mean number of categories from the concentration parameter for the DPP.</title>
    
        <description>
            <p>
            This function calculates the expected number of parameter categories for a given concentration parameter
            and number of elements under the Dirichlet process prior.
            </p>
        </description>

        <usage>
            <![CDATA[
             fnDPPMeanFromConc( RealPos concentration, RealPos num_elements )
             ]]> 
        </usage>
    
        <argument>
            <label>concentration</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The concentration parameter of the DPP.</description>
            <valueType>RealPos</valueType>
        </argument>
        <argument>
            <label>num_elements</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The number of elements.</description>
            <valueType>RealPos</valueType>
        </argument>

        <returnValue>RealPos, Real, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            This function computes the expected number of parameter categories (k) for
            a given number of elements (N) and a given concentration parameter (a) based on the formula given
            in Liu (1996). (See also McAuliffe et al. 2006, Jara et al. 2007, and Heath et al. 2012.)
            </p>
            <p>
            E(k | a, N) = ∑[ a / (a + i - 1) ]
            </p>
        </details>

        <example>
            <![CDATA[
	 ## number of DPP elements
	 N <- 10
 
	 ## prior mean number of categories
	 a <- 3.3015
 
	 ## concentration parameter of the DPP
	 k <- fnDPPMeanFromConc(a, N)
 
	 ## G_0 distribution
	 g_0 = dnExponential(1.0)
 
	 ## DPP distribution constructior
	 rates ~ dnDPP(a, g_0, N)
             ]]>

        </example>

        <reference>
            <citation>
                Liu JS. 1996. Nonparametric hierarchical Bayes via sequential imputa- tions. Ann Stat. 3:911–930.
            </citation>
        </reference>
        <reference>
            <citation>
                McAuliffe JD, Blei DM, Jordan MI. 2006. Nonparametric empirical Bayes for the Dirichlet process mixture model. Stat Comput. 16: 5–14.
            </citation>
        </reference>
        <reference>
            <citation>
            	Jara A, Garcia-Zattera MJ, Lesaffre E. 2007. A Dirichlet process mixture model for the analysis of correlated binary responses. Comput Stat Data Anal. 51:5402–5415.
            </citation>
        </reference>
        <reference>
            <citation>
            	Heath TA, Holder MT, Huelsenbeck JP. 2012. A Dirichlet process prior for estimating lineage-specific substitution rates. Mol. Biol. Evol. 29(3):939–955. 
            </citation>
        </reference>

        <author>Tracy A. Heath</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>fnDPPConcFromMean</entry>
            <entry>dnDPP</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>
