=== xingguangli/revbayes/help_html/rb-help-entry.xsd
<?xml version="1.0"?>    
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.revbayes.com/schema/help-entry" >
   
    <xs:element name="revbayes-help">
        <xs:annotation>
            <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                Fill in with more help documentation ...
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="function-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:annotation>
                                    <xs:documentation>Full description, text is sectioned by paragraphs.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="usage"/>
                            <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Arguments is optional since functions can have 0 parameters.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="label"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="argumentType"/>
                                        <xs:element type="xs:string" name="valueType"/>  
                                        <xs:element type="xs:string" name="option" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="defaultValue" minOccurs="0"/>                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="returnValue"/>
                                                        
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>Text sectioned with paragraphs.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="example" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Typically, example text will be wrapped in a CDATA section to avoid having to escape special characters.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                        <xs:element type="xs:anyURI" name="url" minOccurs="0"/>
                                        <xs:element type="xs:string" name="doi" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="author"/>
                            
                            <xs:element name="seeAlso" minOccurs="0">                                
                                <xs:annotation>
                                    <xs:documentation>The xslt page will try to auto generate links to the referred help entries, therefore
                                        only exact names of help items should be listed here (case sensitive).</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="entry" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="type-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="memberMethod" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="methodName"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="usage"/>
                                        <xs:element type="xs:string" name="methodType"/>
                                        <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="label"/>
                                                    <xs:element type="xs:string" name="description"/>
                                                    <xs:element type="xs:string" name="argumentType"/>
                                                    <xs:element type="xs:string" name="valueType"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="returnValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="author"/>
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xingguangli/revbayes/deprecated/help/rcat.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>rcat</name>

        <title>Random Variables from The Categorical Distribution</title>
    
        <description>
            <p>
            This function generates random draws from the categorical distribution.
            The desired number of random draws is specified by the argument n, and
            the probability of the outcomes is specified by the simplex parameter p.
            The outcomes are labeled from 1 to K, and each outcome i has the
            probability given by element i in the simplex p.
            </p>
        </description>

        <usage>
            <![CDATA[
             rcat( Natural n, Simplex p )
             ]]> 
        </usage>
    
        <argument>
            <label>n</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The desired number of draws.</description>
            <valueType>Natural</valueType>
            <defaultValue>1</defaultValue>
        </argument>
        <argument>
            <label>p</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The probability of the outcomes.</description>
            <valueType>Simplex</valueType>
        </argument>

        <returnValue>Natural[]</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            See dnCat for details.
            </p>
        </details>

        <example>
            <![CDATA[
             # Draw 10 values from a categorical distribution
             # with the outcome probabilities being 0.1, 0.2,
             # 0.3, and 0.4, respectively. Examine the value
             # afterwards. Note that the outcomes will be
             # in the space { 1, 2, 3, 4 }
             x <- rcat( 10, simplex(0.1, 0.2, 0.3, 0.4) )
             x
             ]]>

        </example>

        <author>Fredrik Ronquist</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>dnCat</entry>
            <entry>dcat</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help_old/cbdp.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
    xmlns="http://www.revbayes.org/schema/help-entry"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>

        <name>cBDP</name>

        <title>Constant-rate birth-death process</title>

        <description>
            <p>
                The constant-rate birth-death process species a prior probability distribution on time trees. The birth (speciation) and death (extinction)
                rates are assumed to be constant over time. Unlike some implementations, cBDP does not constrain the birth rate to be larger than the death
                rate.
            </p>
        </description>

        <usage>
        <![CDATA[
        ConstBDProcess cBDP(
                             RealPos        lambda,
                             RealPos        mu = 0.0,
                             RealPos        origin,
                             Probability    rho = 1.0,
                             String         samplingStrategy="uniform",
                             String         condition="survival",
                             Natural        nTaxa,
                             Vector<String> names,
                             Vector<Clade>  constraints
                           )
        ]]>
        </usage>

        <argument>
            <label>lambda</label>
            <argumentType>dynamic</argumentType>
            <description>Birth (speciation) rate.</description>
            <valueType>Positive real number</valueType>
        </argument>
        <argument>
            <label>mu</label>
            <description>Death (extinction) rate.</description>
            <argumentType>dynamic</argumentType>
            <valueType>Positive real number</valueType>
        </argument>
        <argument>
            <label>origin</label>
            <description>The time of the process since the origin, i.e., the length of the stem branch plus the crown age.</description>
            <argumentType>dynamic</argumentType>
            <valueType>Positive real number</valueType>
        </argument>
        <argument>
            <label>rho</label>
            <description>The taxon sampling probability/fraction.</description>
            <argumentType>dynamic</argumentType>
            <valueType>Positive real number between 0.0 and 1.0</valueType>
            <defaultValue>1.0</defaultValue>
        </argument>
        <argument>
            <label>samplingStrategy</label>
            <description>The sampling strategy used if the taxon sampling is incomplete.</description>
            <argumentType>fixed</argumentType>
            <valueType>String</valueType>
            <option>"uniform"</option>
            <option>"diversified"</option>
            <defaultValue>"uniform"</defaultValue>
        </argument>
        <argument>
            <label>condition</label>
            <description>Conditioning of the process. For details, see below.</description>
            <argumentType>fixed</argumentType>
            <valueType>String</valueType>
            <option>"time"</option>
            <option>"survival"</option>
            <option>"tree"</option>
            <option>"nTaxa"</option>
            <defaultValue>time</defaultValue>
        </argument>
        <argument>
            <label>nTaxa</label>
            <argumentType>fixed</argumentType>
            <description>The number of taxa. This is only needed for simulation/initialization purposes when a tree with exactly n taxa is needed in the model.</description>
            <valueType>Natural number</valueType>
        </argument>
        <argument>
            <label>names</label>
            <argumentType>fixed</argumentType>
            <description>The taxon labels that will be applied to the simulated tree.</description>
            <valueType>Vector of strings</valueType>
        </argument>
        <argument>
            <label>constraints</label>
            <argumentType>fixed</argumentType>
            <description>The topological constraints applied to the tree, i.e., conditioning on the occurence of the split between the clade and the remaining tree.</description>
            <valueType>Vector of clades</valueType>
            <defaultValue>NULL</defaultValue>
        </argument>

        <returnValue>TimeTree</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
                The implementation of the constant-rate birth-death process is based on Nee et al. (1994). The unconditioned process results in an improper probability
                distribution, so the process needs to be conditioned on something. Possibilities include to condition the process on the time (duration), on survival
                (non-extinction), on obtaining a tree, or on obtaining the number of observed taxa. The condition of the process is controlled by the 'condition' 
                parameter.
            </p>
            <p>
                The process gives rise to trees with extinct branches, but observed trees typically do not include extinct branches. As implemented here, we
                assume that it is trees without extinct branches, so-called reconstructed trees, that we observe. The probability distribution is modified accordingly.
            </p>
            <p>
                It is commonly the case that the observed tree does not include all tips. The included tips may have been sampled uniformly at random from the available
                complete tree. A particularly common bias is that the investigator has tried to maximize the diversity in the sampled tree, by including tips that are as
                distantly related to each other as possible. This is referred to as diversified sampling. It is critical to model the sampling process
                correctly to obtain accurate estimates of the birth and death rates (Hoehna et al. 2011); particularly the estimate of the death rate is sensitive to
                violations of the sampling assumptions.
            </p>

        </details>

        <example>
        <![CDATA[
        trueTree <- readTrees("data/primate.tree")[1]
        
        names <- trueTree.names()
        taxaCount <- names.size()
        
        # Birth-Death process priors
        speciation ~ exponential(0.1)
        extinction ~ exponential(0.1)
        org ~ unif(0.0,50.0)
        
        # moves for the birth-death parameters
        moves[1] <- mScale(speciation, lambda=1, tune=true, weight=2)
        moves[2] <- mScale(extinction, lambda=1, tune=true, weight=2)
        moves[3] <- mSlide(org, delta=1.0, weight=2.0)
       
        # tree from birth-death process
        tau ~ cBDP(origin=org, lambda=speciation, mu=extinction, nTaxa=taxaCount, names=names)
       
        tau.clamp( trueTree )
        
        monitors[1] <- modelmonitor(filename="testBirthDeath.log",printgen=10, separator = "	")
        monitors[2] <- screenmonitor(printgen=1000, separator = "	", speciation)
        
        mymodel <- model(tau)
        
        mymcmc <- mcmc(mymodel, monitors, moves)
        
        mymcmc.burnin(generations=20000,tuningInterval=100)
        mymcmc.run(generations=200000)
        mymcmc.operatorSummary()
        ]]>
       
        </example>

        <reference>
            <citation>
                Nee, S., May, R.M., and Harvey, P.H. 1994. The Reconstructed Evolutionary Process. Philosophical Transactions: Biological Sciences, 344, 305-311
            </citation>
            <url>http://rstb.royalsocietypublishing.org/content/344/1309/305.short</url>
            <doi>10.1098/rstb.1994.0068</doi>
        </reference>
        <reference>
            <citation>
                HÃ¶hna, S., Stadler, T., Ronquist, F, and Britton, T. 2011. Inferring speciation and extinction rates under different species sampling scheme.s Molecular Biology and Evolution, 28, 2577-2589.
            </citation>
            <url>http://mbe.oxfordjournals.org/content/28/9/2577.short</url>
            <doi>10.1093/molbev/msr095</doi>
        </reference>
        
        <author>Sebastian Hoehna</author>
    
        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore
            only exact names of help items should be listed here (case sensitive) -->
            <entry>diversityDependentBirthDeathProcess</entry>
        </seeAlso>
    
        

    </function-help-entry>
</revbayes-help>

=== xingguangli/revbayes/deprecated/help_old/expBranchTree.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>expbranchtree</name>

        <title>Branch-wise exponentiated averages of a real-valued quantitative trait.</title>
    
        <description>
            <p>
            This function takes a specific entry of a multivariate quantitative trait and calculates the branch-wise averages of its exponential. The result is a vector of positive real values associated to each branch of the tree: these can be thought of as branch-rates, explicitly calculated from a model of trait evolution. This method is used for correlating trait and substitution rate evolution along a phylogeny (Lartillot and Poujol, 2011).
            </p>
        </description>

        <usage>
            <![CDATA[
             expbranchtree( TimeTree tree, MultivariateRealNodeValTree process, Real offset = 0, Natural traitindex = 0 )
             ]]> 
        </usage>
    
        <argument>
            <label>tree</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A time-calibrated phylogeny.</description>
            <valueType>TimeTree</valueType>
        </argument>
        <argument>
            <label>process</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A real-values multivariate process of trait evolution.</description>
            <valueType>MultivariateRealNodeValTree</valueType>
        </argument>
        <argument>
            <label>offset</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>A real-valued offset (optional argument, generally not used).</description>
            <valueType>Real</valueType>
            <defaultValue>0</defaultValue>
        </argument>
        <argument>
            <label>traitindex</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>Index specifying which entry of the multivariate process should be used for calculating branch-wise exponential averages.</description>
            <valueType>Natural</valueType>
            <defaultValue>0</defaultValue>
        </argument>

        <returnValue>RealPos[], ModelObject, RevObject</returnValue>

        <details>
            <p>
            This function generalizes the idea behind autocorrelated log-normally distributed rates (such as developed in the dnACLN function, see Thorne et al, 1998), which is to model the instant rate of substitution as the exponential of a Brownian motion. Here, a multivariate Brownian motion is considered, instead of a univariate model. This allows coupling between trait evolution and rate variation among branches.
            </p>
        </details>

        <example>
            <![CDATA[

		# load tree
		tree <- readTrees("data/chronoplac40.tree")[1]

		# covariance matrix with free scaling factor kappa
		kappa ~ dnLogUniform(min=0.001,max=1000)
		Sigma ~ dnInvWishart(dim=2, kappa=kappa, df=3)

		# bivariate Brownian process along the tree
		X ~ dnBrownianMultiVariate(tree,sigma=Sigma)

		# first component of the Brownian model gives the *log* of the substitution rate
		# so we take the exponential and average over branches
		# traitindex = 1: because we want to take the exponential of the first component of the multivariate Brownian process
		rate := expbranchtree(tree=psi,process=X,traitindex=1)

		# rate can now be used as the branchRate argument of a relaxed clock model
		... 
             ]]>

        </example>

        <reference>
            <citation>
                Lartillot N and Poujol R. 2011. A phylogenetic model for investigating correlated evolution of substitution rates and continuous phenotypic characters. Mol Biol Evol 28:729-744.
            </citation>
        </reference>

        <author>Nicolas Lartillot</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>similar function</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/floor.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>floor</name>

        <title>Floor value of a number.</title>
    
        <description>
            <p>
            The 'floor' function maps the value of a number to the largest preceding integer.
            </p>
        </description>

        <usage>
            <![CDATA[
             floor( RealPos x )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The number whose floor value needs to be obtained.</description>
            <valueType>RealPos</valueType>
        </argument>

        <returnValue>Natural, Integer, RevObject</returnValue>


        <example>
            <![CDATA[
             # compute the floor value of a real number
             number <- 3.4 
             floor(number)         
             ]]>
		</example>
		
        <author>Bastien Boussau</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>ceil</entry>
            <entry>abs</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>
