=== xingguangli/revbayes/help_html/rb-help-entry.xsd
<?xml version="1.0"?>    
<xs:schema attributeFormDefault="unqualified" 
           elementFormDefault="qualified" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.revbayes.com/schema/help-entry" >
   
    <xs:element name="revbayes-help">
        <xs:annotation>
            <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                Fill in with more help documentation ...
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="function-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:annotation>
                                    <xs:documentation>Full description, text is sectioned by paragraphs.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="usage"/>
                            <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Arguments is optional since functions can have 0 parameters.</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="label"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="argumentType"/>
                                        <xs:element type="xs:string" name="valueType"/>  
                                        <xs:element type="xs:string" name="option" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="defaultValue" minOccurs="0"/>                                        
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="returnValue"/>
                                                        
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded">
                                            <xs:annotation>
                                                <xs:documentation>Text sectioned with paragraphs.</xs:documentation>
                                            </xs:annotation>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="example" minOccurs="0">
                                <xs:annotation>
                                    <xs:documentation>Typically, example text will be wrapped in a CDATA section to avoid having to escape special characters.</xs:documentation>
                                </xs:annotation>
                            </xs:element>
                            
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                        <xs:element type="xs:anyURI" name="url" minOccurs="0"/>
                                        <xs:element type="xs:string" name="doi" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            
                            <xs:element type="xs:string" name="author"/>
                            
                            <xs:element name="seeAlso" minOccurs="0">                                
                                <xs:annotation>
                                    <xs:documentation>The xslt page will try to auto generate links to the referred help entries, therefore
                                        only exact names of help items should be listed here (case sensitive).</xs:documentation>
                                </xs:annotation>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="entry" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                
                <xs:element name="type-help-entry" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>Each help file typically consists of either a "function section" or "type-section". In the rare case when a lowercase 
                            function name is equal to a lowercase type name, both sections have to be specified in the same file. 
                
                            Fill in with more help documentation ...
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element type="xs:string" name="name"/>
                            <xs:element type="xs:string" name="title"/>
                            <xs:element name="description">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="memberMethod" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="methodName"/>
                                        <xs:element type="xs:string" name="description"/>
                                        <xs:element type="xs:string" name="usage"/>
                                        <xs:element type="xs:string" name="methodType"/>
                                        <xs:element name="argument" maxOccurs="unbounded" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element type="xs:string" name="label"/>
                                                    <xs:element type="xs:string" name="description"/>
                                                    <xs:element type="xs:string" name="argumentType"/>
                                                    <xs:element type="xs:string" name="valueType"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element type="xs:string" name="returnValue"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="details">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="p" maxOccurs="unbounded" minOccurs="0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="author"/>
                            <xs:element name="reference" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="citation"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== xingguangli/revbayes/deprecated/help/fnDPPConcFromMean.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>fnDPPConcFromMean</name>

        <title>The expected value of the concentration parameter from the mean number of parameter categories for the DPP distribution.</title>
    
        <description>
            <p>
            This function calculates the approximate expected value for the Dirichlet process prior distribution concentration parameter given a mean number of parameter categories for a specified number of elements.
            </p>
        </description>

        <usage>
            <![CDATA[
             fnDPPConcFromMean( RealPos num_cats, RealPos num_elements )
             ]]> 
        </usage>
    
        <argument>
            <label>num_cats</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The mean number of rate categories.</description>
            <valueType>RealPos</valueType>
        </argument>
        <argument>
            <label>num_elements</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The number of elements in the DPP distribution.</description>
            <valueType>RealPos</valueType>
        </argument>

        <returnValue>RealPos, Real, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            This function computes an approximation of the expected value of the concentration parameter (a) for 
            a given number of elements (N) and a given number of parameter categories (k) based on the formula given
            in Liu (1996). (See also McAuliffe et al. 2006, Jara et al. 2007, and Heath et al. 2012.)
            </p>
        </details>

        <example>
            <![CDATA[
	 ## number of DPP elements
	 N <- 10
 
	 ## prior mean number of categories
	 k <- 8
 
	 ## concentration parameter of the DPP
	 a <- fnDPPConcFromMean(k, N)
 
	 ## G_0 distribution
	 g_0 = dnExponential(1.0)
 
	 ## DPP distribution constructior
	 rates ~ dnDPP(a, g_0, N)
             ]]>

        </example>

        <reference>
            <citation>
                Liu JS. 1996. Nonparametric hierarchical Bayes via sequential imputa- tions. Ann Stat. 3:911–930.
            </citation>
        </reference>
        <reference>
            <citation>
                McAuliffe JD, Blei DM, Jordan MI. 2006. Nonparametric empirical Bayes for the Dirichlet process mixture model. Stat Comput. 16: 5–14.
            </citation>
        </reference>
        <reference>
            <citation>
            	Jara A, Garcia-Zattera MJ, Lesaffre E. 2007. A Dirichlet process mixture model for the analysis of correlated binary responses. Comput Stat Data Anal. 51:5402–5415.
            </citation>
        </reference>
        <reference>
            <citation>
            	Heath TA, Holder MT, Huelsenbeck JP. 2012. A Dirichlet process prior for estimating lineage-specific substitution rates. Mol. Biol. Evol. 29(3):939–955. 
            </citation>
        </reference>

        <author>Tracy A. Heath</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>fnDPPMeanFromConc</entry>
            <entry>dnDPP</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/fnJC.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>fnJC</name>

        <title>The Jukes and Cantor function to create a rate matrix.</title>
    
        <description>
            <p>
            The function fnJC creates the simplest rate matrix on an alphabet with a given number of states.
            </p>
        </description>

        <usage>
            <![CDATA[
             fnJC( Natural numStates )
             ]]> 
        </usage>
    
        <argument>
            <label>numStates</label>
            <argumentPassingMethod>by-value</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>the number of states in the alphabet.</description>
            <valueType>Natural</valueType>
        </argument>

        <returnValue>RateMatrix, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
            The Jukes and Cantor model (1969) is the simplest substitution model and requires no parameter. It assumes equal transition rates among any two states. It works on alphabets of any size but was initially described by Jukes and Cantor for DNA (4 states). It is fast but makes a number of usually unrealistic assumptions, including equal base frequencies in the sequences, and equal mutation rates.
            </p>
        </details>

        <example>
            <![CDATA[
             # Let's simulate data using a Jukes and Cantor model on an alphabet with 5 states.
             matrix <- fnJC(numStates=5)
             print(matrix)
             
             # We build a tree with 3 leaves
             n_species <- 3
             for (i in 1:n_species) {
        			s_names[i] = "Species_"+i
			 }
             speciation ~ dnExponential(10.0)
			 extinction ~ dnExponential(10.0)
			 tree_height ~ dnUnif(0,1.0)
			 speciesTree ~ dnBDP(lambda=speciation, mu=extinction, origin=tree_height, nTaxa=n_species, names=s_names)
             
             # Let's simulate 30 sites over this tree, starting from a sequence all in the first state.
             # Root frequencies: all in the first state
             frequencyFirstState <- 1.0
             rootFrequencies <- simplex(frequencyFirstState, 0.0, 0.0, 0.0, 0.0)
             n_sites=30
             aln ~ dnPhyloCTMC(tree=speciesTree, Q=matrix, rootFrequencies=rootFrequencies, nSites=n_sites, type="Standard")
			
			 # Now we can have a look at the sequences in the resulting alignment
			 aln.show()             
             
             # And we can compute the log probability of the alignment
             aln.lnProbability()
             ]]>

        </example>

        <reference>
            <citation>
                T.H. Jukes, C.R. Cantor. 1969. Evolution of protein molecules. 
In Mammalian protein metabolism, Vol. III, pp. 21-132.
            </citation>
        </reference>

        <author>Bastien Boussau</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>fnGTR</entry>
            <entry>fnHKY</entry>
            <entry>fnF81</entry>
            <entry>fnPomo</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/mean.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>mean</name>

        <title>Arithmetic mean of a vector of numbers</title>
    
        <description>
            <p>
                The 'mean' function computes the arithmetic mean of a vector of real numbers.
                The arithmetic mean simply computes the average by summing all the values together and divides them by the number of values.
            </p>
        </description>

        <usage>
            <![CDATA[
             mean( Real[] x )
             ]]> 
        </usage>
    
        <argument>
            <label>x</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>This is the vector of real number.</description>
            <valueType>Real[]</valueType>
        </argument>

        <returnValue>Real, RevObject</returnValue>

        <example>
            <![CDATA[
             # compute the mean of some random draws from a normal distribution
             x <- rnorm(n=10, 5,1)
             mean(x)
             ]]>

        </example>

        <author>Sebastian Hoehna</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>sum</entry>
            <entry>var</entry>
        </seeAlso>


    </function-help-entry>
</revbayes-help>

=== xingguangli/revbayes/deprecated/help/dnDPP.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <distribution-help-entry>

        <name>dnDPP</name>

        <title>The Dirichlet process prior distribution</title>

        <description>
            <p>
            This function returns a Dirichlet process prior (DPP) distribution. 
            </p>
        </description>
    
        <constructor-help-entry>
        

            <usage>
                <![CDATA[
                 dnDPP( RealPos concentration, Distribution__<type> baseDistribution, Natural numElements )
                 ]]> 
            </usage>
        
            <argument>
                <label>concentration</label>
                <argumentPassingMethod>by-const-reference</argumentPassingMethod>
                <argumentNodeType>any-DAG-node</argumentNodeType>
                <description>The concentration parameter of the DPP (can be computed using fnDPPConcFromMean function).</description>
                <valueType>RealPos</valueType>
            </argument>
            <argument>
                <label>baseDistribution</label>
                <argumentPassingMethod>by-const-reference</argumentPassingMethod>
                <argumentNodeType>any-DAG-node</argumentNodeType>
                <description>The DPP base distribution. This also gives the Rev type of the stochastic node created with this distribution.</description>
                <valueType>Distribution__Any (See details below)</valueType>
            </argument>
            <argument>
                <label>numElements</label>
                <argumentPassingMethod>by-value</argumentPassingMethod>
                <argumentNodeType>any-DAG-node</argumentNodeType>
                <description>The number of elements distributed by the DPP.</description>
                <valueType>Natural</valueType>
            </argument>

            <returnValue>Dist_dpp, Distribution__Any[], Distribution, RevObject</returnValue>

            <details>
                <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
                <p>
                This function constructs a Dirichlet process prior distribution. The DPP is used to model
                mixtures of data. For example, this distribution is used as a prior on lineage-specific
                substitution rates as a model for relaxing the assumption of a strict molecular clock (Heath et al. 2012).
                </p>
                <p>
                In RevBayes this distribution is templated, meaning that it can be used for different types of
                parameters. Thus, depending on the type of the base distribution, the DPP can be a prior on elements 
                with Real, RealPos, Integer, Natural, Probability, or Simplex parameters. 
                The distribution constructor creates a stochastic node that is a vector of N elements of the type listed above,
                were N is the number of elements distributed under the DPP. 
                </p>
                <p>
                The DPP is an infinite mixture model and takes 2 parameters: the concentration parameter (a) and 
                the base distribution (G_0). The concentration parameter influences the number of parameter categories
                and the base distribution is the prior distribution from which parameter values for each
                category are drawn. For more information see: Ferguson (1973); Antoniak (1974); Lartillot and Philippe (2004);
                Huelsenbeck et al. (2006); Ané et al. (2007); Huelsenbeck and Suchard (2007); Heath et al. (2012); 
                Heath (2012)
                </p>
            </details>

            <example>
                <![CDATA[
	 ## number of DPP elements
	 N <- 10
 
	 ## prior mean number of categories
	 k <- 8
 
	 ## concentration parameter of the DPP
	 a <- fnDPPConcFromMean(k, N)
 
	 ## G_0 distribution
	 G_0 = dnExponential(1.0)
 
	 ## DPP distribution constructior
	 rates ~ dnDPP(a, G_0, N)
                 ]]>

            </example>

            <reference>
				<citation>
					Ané C, Larget B, Baum DA, Smith SD, Rokas A. 2007. Bayesian estimation of concordance among gene trees. Mol Biol Evol. 24: 412–426.
            	</citation>
            </reference>
            <reference>
				<citation>
					Antoniak CE. 1974. Mixtures of Dirichlet processes with applications to non-parametric problems. Ann Stat. 2:1152–1174.
            	</citation>
            </reference>
            <reference>
				<citation>
					Ferguson TS. 1973. A Bayesian analysis of some nonparametric problems. Ann Stat. 1:209–230.
            	</citation>
            </reference>
            <reference>
				<citation>
					Heath TA, Holder MT, Huelsenbeck JP. 2012. A Dirichlet process prior for estimating lineage-specific substitution rates. Mol. Biol. Evol. 29(3):939–955. 
            	</citation>
            </reference>
            <reference>
				<citation>
					Heath TA. 2012. A hierarchical Bayesian model for calibrating estimates of species divergence times. Syst. Biol. 61:793-809.
            	</citation>
            </reference>
            <reference>
				<citation>
					Huelsenbeck JP, Jain S, Frost SWD, Pond SLK. 2006. A Dirichlet process model for detecting positive selection in protein-coding DNA sequences. Proc Natl Acad Sci U S A. 103:6263–6268.
            	</citation>
            </reference>
            <reference>
				<citation>
					Huelsenbeck JP, Suchard M. 2007. A nonparametric method for accommodating and testing across-site rate variation. Syst Biol. 56:975–987.
            	</citation>
            </reference>
            <reference>
				<citation>
					Lartillot N, Philippe H. 2004. A Bayesian mixture model for across-site heterogeneities in the amino-acid replacement process. Mol Biol Evol.21:1095–1109.
				</citation>
            </reference>

            <author>Tracy A. Heath</author>

            <seeAlso>
                <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
                <entry>dnMixture</entry>
                <entry>fnDPPConcFromMean</entry>
                <entry>mvDPPAllocateAuxGibbs</entry>
                <entry>mvDPPGibbsConcentration</entry>
                <entry>mvDPPScaleCatAllocateAux</entry>
                <entry>mvDPPScaleCatVals</entry>
            </seeAlso>


        </constructor-help-entry>
    
    

    </distribution-help-entry>

</revbayes-help>

=== xingguangli/revbayes/deprecated/help/power.xml
<?xml version="1.0"?>
<?xml-stylesheet href="lib/help.xsl" type="text/xsl"?>

<revbayes-help
	xmlns="http://www.revbayes.org/schema/help-entry"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.revbayes.org/schema/help-entry lib/rb-help-entry.xsd"
>
    <function-help-entry>
    
        <name>power</name>

        <title>Compute nth power</title>
    
        <description>
            <p>
            'power' raises 'base' to the 'exponent' power
            </p>
        </description>

        <usage>
            <![CDATA[
             power( Real[] base, Real exponent )
             ]]> 
        </usage>
    
        <argument>
            <label>base</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The exponent's base value(s)</description>
            <valueType>Real or Real[]</valueType>
        </argument>
        <argument>
            <label>exponent</label>
            <argumentPassingMethod>by-const-reference</argumentPassingMethod>
            <argumentNodeType>any-DAG-node</argumentNodeType>
            <description>The exponent's power</description>
            <valueType>Real</valueType>
        </argument>

        <returnValue>Real or RealPos[], ModelObject, RevObject</returnValue>

        <details>
            <!-- Since this section can be lengthy, the text is sectioned with <p> tags -->
            <p>
                'power' returns the value(s) of 'base' raised to the power 'exponent'. If 'base' is a vector, then 'power' is applied element-wise to 'base'. When 'base' is RealPos, all values of 'exponent' are accepted. For negative Real values of 'base', values of 'exponent' that give non-complex powers are valid. In general, 'power(base,exponent)' is equivalent to applying the '^' operator, e.g. 'base^exponent'. 
            </p>
        </details>

        <example>
            <![CDATA[
            > power(0.01, 0.5)
                0.1
            > power([1,2,3], 2)
                [ 1, 4, 9 ]
            ]]>

        </example>

        <author>Michael Landis</author>

        <seeAlso>
            <!-- The xslt page will try to auto generate links to the referred help entries, therefore only exact names of help items should be listed here (case sensitive) -->
            <entry>sqrt</entry>
        </seeAlso>


    </function-help-entry>

</revbayes-help>
